### PR TITLE
fix(dependency-information): update on version change

### LINKED ISSUE #61: dependancy view not updated
* **What are you trying to do?**
Switching between versions of an artifact using the dropdown menu, the pom file updates but the right hand column (dependancy view?) does not reflect the change in version.

* **What feature or behavior is this required for?**
Looking at the differences between poms to understand dependency differences

### PR DESCRIPTION
**Pull request by simon04**
Fixes #61.

### CODE REVIEW

**Comment by simon04** [comment]
@SirMaster, @DarthHater: ping! ⏰ Any update on this PR and my other PRs?

**Comment by DarthHater** [comment]
Thanks for the ping! I'll take a gander at this over the next few days @simon04

**Comment by SirMaster** [comment]
@simon04  my apologies for the delay, we have been a bit busy. I recently fixed this, though add some more filtering out of the changes. 

It should be released soon.

**Comment by DarthHater** [comment]
I believe this is addressed now, correct @SirMaster ?

**Comment by SirMaster** [comment]
Correct!

**Pull request closed without merging**
