### PR TITLE
Short syntax of dependency declaration for Kotlin DSL

### PR DESCRIPTION
**Pull request by gildor**
use the same syntax for dependency declaration for Gradle Kotlin DSL as for Groovy DSL

### CODE REVIEW

**Comment by DarthHater** [comment]
Having not much experience with this in specific, is this just a preference or is it preferred that it does it this way @gildor ? Really appreciate the contribution (sign the CLA :) )

**Comment by gildor** [comment]
CLA signed

**Comment by DarthHater** [comment]
@gildor any link to any example documentation that shows this as the preferred format? Just want it for a good trail on why we made the change.

**Comment by DarthHater** [comment]
Also, you might want to add a test case for this to:

https://github.com/sonatype-nexus-community/search-maven-org/blob/master/src/app/artifact/dependency-information/dependency-information.component.spec.ts#L61

@SirMaster and I got our test suite working (or it should anyways :) ), and it would be nice to add another case for this!

**Comment by eskatos** [comment]
👍 to make the Gradle Kotlin DSL snippet closer to the Gradle Groovy DSL one. There's no reason they should be that different.

Here is the reference documentation on adding dependencies, the short notation is preferred: https://docs.gradle.org/current/userguide/declaring_dependencies.html

**Comment by DarthHater** [comment]
@eskatos thanks for that! I can totally make this change myself, but it would be cooler if one of you fixes the conflict and sends a PR, that way y'all can get credit :)

**Comment by gildor** [comment]
PR updated with fixed conflicts, tests and rebased

**Comment by gildor** [comment]
If we talking about personal preferences I have one: use `"` instead of `'` because it allows to extract version to a variable and use string templates in Groovy, but almost everywhere in Gradle docs and third-party plugins used apostrophes that do not allow to use string templates.
Maybe @eskatos have some opinion about thi

**Comment by DarthHater** [comment]
@gildor @eskatos should it be `implementation` instead of `compile`? We had updated the Groovy one to that, curious if it's the same deal with Kotlin or maybe not?

**Comment by ilya-g** [comment]
@gildor Please do, there's already an issue #72 about that.

**Comment by gildor** [comment]
@ilya-g Done, see PR #74

**Pull request merged**
