### PR TITLE
Added link to environment config

### PR DESCRIPTION
**Pull request by MrIndiaDev**
Added link to environment config

This pull request makes the following changes:
- Added link to environment config
- Added alternate option for using data url on external system through reverse proxy server

### CODE REVIEW

**Comment by DarthHater** [comment]
@MrIndiaDev I got a couple questions for you unrelated to this PR, but this seems to be the only way to really reach out to you. We noticed you've deployed search.maven.org and used a few hacks to get it working under a new URL. Being that you have the site deployed with our branding, it is at best a bit misleading, and essentially a mirror currently. I am mostly curious if you are using that site for just testing or what your long term plan for it is? You can reach out to me privately if you'd like, I was just unable to find a way to do so easily.

This change itself is innocuous PS, if you sign the CLA I'll get it merged when we have a chance!

**Comment by MrIndiaDev** [comment]
@DarthHater To answer your questions
- I was just testing the CORS hack I have done. 
- In no way I am planning to maintain this deployment for a longer, it was just a short term assignment that I picked out of curiosity to see the latest development done on it. 
- I'll sign the CLA asap.

**Comment by DarthHater** [comment]
@MrIndiaDev please sign the CLA as soon as you get a chance. I went ahead and merged this as the change is effectively trivial, but helpful to others! Thanks for the contribution! Also, thanks for the explanation. We were all kind of wondering what you were up to, sort of hard to read minds on the internets :)

**Comment by MrIndiaDev** [comment]
CLA signed, Thanks

**Pull request merged**
