### PR TITLE
update gradle logo to newest version

### PR DESCRIPTION
**Pull request by jlstrater**
We recently published new logos and brand guidelines to [gradle.com/brand](https://gradle.com/brand).

This pull request makes the following changes:
* updates the logo used on the right sidebar for the Groovy Gradle DSL.

### CODE REVIEW

**Comment by SirMaster** [comment]
@jlstrater thank you for the PR, we are looking and testing the PR and hope to get it merged soon. Nice logo!

**Comment by SirMaster** [comment]
Thanks again, we just merged this and hope to release it soon.

**Comment by jlstrater** [comment]
Hi @SirMaster. It looks like this was closed and not merged. or do you have a release branch I can't see?

**Comment by SirMaster** [comment]
hi @jlstrater this merged to master already, we merged this public PR to our internal private one and that kicked of an automated build. 

Are you currently not seeing it on the site?

**Comment by lacasseio** [comment]
A good example of this is shown here: https://search.maven.org/artifact/com.google.guava/guava/22.0/bundle

**Pull request closed without merging**
